/**
 * AI QUALITY MONITOR (K18)
 * Automatically scores 100% of customer interactions using AI.
 * Evaluates calls, chats, and emails against a standardized QA rubric.
 * Stores results as CrmQaScore records with metadata.autoGenerated = true.
 * Supports calibration by comparing AI scores against human QA scores.
 */

import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/db';
import { logger } from '@/lib/logger';

// ---------------------------------------------------------------------------
// Lazy OpenAI client
// ---------------------------------------------------------------------------

let _openai: ReturnType<typeof require> | null = null;

function getOpenAI(): { chat: { completions: { create: (params: Record<string, unknown>) => Promise<{ choices?: { message?: { content?: string } }[] }> } } } {
  if (_openai) return _openai;

  if (!process.env.OPENAI_API_KEY) {
    throw new Error('OPENAI_API_KEY not set');
  }

  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { default: OpenAI } = require('openai');
  _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  return _openai;
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface EvaluationCriterion {
  name: string;
  description: string;
  maxScore: number;
  weight: number;
}

export interface AutoEvaluationResult {
  scores: Record<string, number>;
  totalScore: number;
  maxScore: number;
  percentage: number;
  feedback: string;
  strengths: string[];
  improvements: string[];
  complianceFlags: string[];
}

export interface EvaluationReport {
  agentId: string;
  agentName: string;
  period: { start: Date; end: Date };
  totalEvaluations: number;
  avgPercentage: number;
  criteriaAverages: Record<string, number>;
  trend: { date: string; avgScore: number }[];
  topStrengths: string[];
  topImprovements: string[];
  complianceIssueCount: number;
}

export interface CalibrationResult {
  autoScoreId: string;
  agreement: number;
  criteriaComparison: {
    criterion: string;
    autoScore: number;
    humanScore: number;
    difference: number;
  }[];
  overallAgreement: 'EXCELLENT' | 'GOOD' | 'FAIR' | 'POOR';
}

// ---------------------------------------------------------------------------
// Standard Evaluation Criteria
// ---------------------------------------------------------------------------

/**
 * Returns the standard QA evaluation rubric used for auto-evaluation.
 * Each criterion is scored 1-5 with a weight for the final composite score.
 */
export function getAutoEvaluationCriteria(): EvaluationCriterion[] {
  return [
    {
      name: 'greeting',
      description: 'Proper greeting, introduction, and identification. Sets positive tone.',
      maxScore: 5,
      weight: 0.10,
    },
    {
      name: 'empathy',
      description: 'Shows understanding of customer concerns, active listening, and emotional awareness.',
      maxScore: 5,
      weight: 0.20,
    },
    {
      name: 'resolution',
      description: 'Effectively addresses the customer issue. Provides clear solution or next steps.',
      maxScore: 5,
      weight: 0.25,
    },
    {
      name: 'compliance',
      description: 'Follows required disclosures, script adherence, and regulatory requirements. Products for research only.',
      maxScore: 5,
      weight: 0.15,
    },
    {
      name: 'professionalism',
      description: 'Maintains professional tone, avoids jargon, speaks clearly, and manages difficult situations.',
      maxScore: 5,
      weight: 0.15,
    },
    {
      name: 'accuracy',
      description: 'Information provided is correct. No false promises or incorrect product/policy information.',
      maxScore: 5,
      weight: 0.15,
    },
  ];
}

// ---------------------------------------------------------------------------
// Internal: Run AI evaluation
// ---------------------------------------------------------------------------

/**
 * Common evaluation logic. Takes the interaction text and evaluates it
 * against the QA rubric using OpenAI.
 */
async function runAiEvaluation(
  interactionText: string,
  interactionType: 'call' | 'chat' | 'email',
): Promise<AutoEvaluationResult> {
  const criteria = getAutoEvaluationCriteria();

  const criteriaPrompt = criteria
    .map((c) => `- ${c.name} (max ${c.maxScore}, weight ${(c.weight * 100).toFixed(0)}%): ${c.description}`)
    .join('\n');

  const openai = getOpenAI();

  const completion = await openai.chat.completions.create({
    model: process.env.QA_MONITOR_MODEL || 'gpt-4o-mini',
    messages: [
      {
        role: 'system',
        content:
          `You are a Quality Assurance AI evaluator for Attitudes VIP customer interactions. ` +
          `Evaluate the following ${interactionType} transcript against these criteria:\n\n` +
          `${criteriaPrompt}\n\n` +
          `Respond ONLY with a JSON object containing exactly these fields:\n` +
          `- "scores": object mapping criterion name to score (1-5 integer)\n` +
          `- "feedback": brief overall feedback (max 200 chars)\n` +
          `- "strengths": array of 2-3 things done well (max 100 chars each)\n` +
          `- "improvements": array of 2-3 areas for improvement (max 100 chars each)\n` +
          `- "complianceFlags": array of compliance issues found (empty if none)\n` +
          `\nBe objective and consistent. Score 3 as average, 5 as exceptional, 1 as unacceptable.`,
      },
      {
        role: 'user',
        content: `${interactionType.toUpperCase()} transcript:\n\n${interactionText.slice(0, 6000)}`,
      },
    ],
    max_tokens: 800,
    temperature: 0.1,
  });

  const responseText = completion.choices?.[0]?.message?.content?.trim();
  if (!responseText) {
    throw new Error('Empty response from QA evaluation AI');
  }

  const parsed = JSON.parse(responseText);

  // Validate and normalize scores
  const scores: Record<string, number> = {};
  let totalWeighted = 0;
  let maxWeighted = 0;

  for (const criterion of criteria) {
    const rawScore = Number(parsed.scores?.[criterion.name]) || 3;
    scores[criterion.name] = Math.max(1, Math.min(criterion.maxScore, Math.round(rawScore)));
    totalWeighted += scores[criterion.name] * criterion.weight;
    maxWeighted += criterion.maxScore * criterion.weight;
  }

  const totalScore = Math.round(totalWeighted * 100) / 100;
  const maxScore = Math.round(maxWeighted * 100) / 100;
  const percentage = maxScore > 0 ? Math.round((totalScore / maxScore) * 10000) / 100 : 0;

  return {
    scores,
    totalScore,
    maxScore,
    percentage,
    feedback: typeof parsed.feedback === 'string' ? parsed.feedback.slice(0, 500) : '',
    strengths: Array.isArray(parsed.strengths) ? parsed.strengths.slice(0, 5) : [],
    improvements: Array.isArray(parsed.improvements) ? parsed.improvements.slice(0, 5) : [],
    complianceFlags: Array.isArray(parsed.complianceFlags) ? parsed.complianceFlags.slice(0, 10) : [],
  };
}

// ---------------------------------------------------------------------------
// Internal: Store evaluation as CrmQaScore
// ---------------------------------------------------------------------------

/**
 * Persist an auto-evaluation result as a CrmQaScore record.
 * Creates or finds an "AI Auto-Evaluation" QA form to link the score to.
 */
async function storeEvaluation(
  evaluation: AutoEvaluationResult,
  agentId: string,
  callLogId?: string,
): Promise<string> {
  // Find or create the AI auto-evaluation form
  let form = await prisma.crmQaForm.findFirst({
    where: {
      name: 'AI Auto-Evaluation',
      isActive: true,
    },
    select: { id: true },
  });

  if (!form) {
    const criteria = getAutoEvaluationCriteria();
    form = await prisma.crmQaForm.create({
      data: {
        name: 'AI Auto-Evaluation',
        description: 'Automated quality evaluation powered by AI. Scores all interactions against standard criteria.',
        criteria: criteria.map((c) => ({
          name: c.name,
          maxScore: c.maxScore,
          weight: c.weight,
          description: c.description,
        })) as unknown as Prisma.InputJsonValue,
        isActive: true,
      },
      select: { id: true },
    });
  }

  // Find a system user to attribute the scoring to (use the agent as both for auto-eval)
  const qaScore = await prisma.crmQaScore.create({
    data: {
      formId: form.id,
      agentId,
      scoredById: agentId, // Self-scored by AI on behalf
      callLogId: callLogId || null,
      scores: {
        ...evaluation.scores,
        autoGenerated: true,
        feedback: evaluation.feedback,
        strengths: evaluation.strengths,
        improvements: evaluation.improvements,
        complianceFlags: evaluation.complianceFlags,
      } as unknown as Prisma.InputJsonValue,
      totalScore: evaluation.totalScore,
      maxScore: evaluation.maxScore,
      percentage: evaluation.percentage,
      feedback: evaluation.feedback,
    },
  });

  return qaScore.id;
}

// ---------------------------------------------------------------------------
// Auto-Evaluate Call
// ---------------------------------------------------------------------------

/**
 * Fetch a call's transcription and automatically evaluate it against
 * the QA criteria using AI. Stores the result as a CrmQaScore record.
 *
 * @param callLogId - The CallLog ID to evaluate
 * @returns The evaluation result or null if no transcription found
 */
export async function autoEvaluateCall(
  callLogId: string,
): Promise<AutoEvaluationResult | null> {
  try {
    const callLog = await prisma.callLog.findUnique({
      where: { id: callLogId },
      include: {
        transcription: { select: { fullText: true } },
        agent: { select: { userId: true } },
      },
    });

    if (!callLog?.transcription?.fullText) {
      logger.debug('[AQM] No transcription for call', { callLogId });
      return null;
    }

    if (!callLog.agent?.userId) {
      logger.debug('[AQM] No agent assigned to call', { callLogId });
      return null;
    }

    const evaluation = await runAiEvaluation(callLog.transcription.fullText, 'call');
    await storeEvaluation(evaluation, callLog.agent.userId, callLogId);

    logger.info('[AQM] Call auto-evaluated', {
      callLogId,
      agentId: callLog.agent.userId,
      percentage: evaluation.percentage,
      complianceFlags: evaluation.complianceFlags.length,
    });

    return evaluation;
  } catch (error) {
    logger.error('[AQM] Failed to auto-evaluate call', {
      callLogId,
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

// ---------------------------------------------------------------------------
// Auto-Evaluate Chat
// ---------------------------------------------------------------------------

/**
 * Evaluate a chat conversation by loading its messages and scoring them.
 *
 * @param conversationId - The InboxConversation ID to evaluate
 * @returns The evaluation result or null if insufficient data
 */
export async function autoEvaluateChat(
  conversationId: string,
): Promise<AutoEvaluationResult | null> {
  try {
    const conversation = await prisma.inboxConversation.findUnique({
      where: { id: conversationId },
      include: {
        messages: {
          select: { direction: true, content: true, senderName: true },
          orderBy: { createdAt: 'asc' },
          take: 100,
        },
        assignedTo: { select: { id: true } },
      },
    });

    if (!conversation || conversation.messages.length === 0) {
      logger.debug('[AQM] No messages for conversation', { conversationId });
      return null;
    }

    if (!conversation.assignedTo?.id) {
      logger.debug('[AQM] No agent assigned to conversation', { conversationId });
      return null;
    }

    // Build transcript from messages
    const transcript = conversation.messages
      .map((m) => {
        const sender = m.direction === 'OUTBOUND' ? 'Agent' : 'Customer';
        return `[${sender}${m.senderName ? ` (${m.senderName})` : ''}]: ${m.content}`;
      })
      .join('\n');

    const evaluation = await runAiEvaluation(transcript, 'chat');
    await storeEvaluation(evaluation, conversation.assignedTo.id);

    logger.info('[AQM] Chat auto-evaluated', {
      conversationId,
      agentId: conversation.assignedTo.id,
      percentage: evaluation.percentage,
      messageCount: conversation.messages.length,
    });

    return evaluation;
  } catch (error) {
    logger.error('[AQM] Failed to auto-evaluate chat', {
      conversationId,
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

// ---------------------------------------------------------------------------
// Auto-Evaluate Email
// ---------------------------------------------------------------------------

/**
 * Evaluate an email interaction stored as a CrmActivity record.
 *
 * @param activityId - The CrmActivity ID of the email interaction
 * @returns The evaluation result or null if no content found
 */
export async function autoEvaluateEmail(
  activityId: string,
): Promise<AutoEvaluationResult | null> {
  try {
    const activity = await prisma.crmActivity.findUnique({
      where: { id: activityId },
      select: {
        type: true,
        title: true,
        description: true,
        metadata: true,
        performedById: true,
      },
    });

    if (!activity?.description) {
      logger.debug('[AQM] No content for email activity', { activityId });
      return null;
    }

    if (!activity.performedById) {
      logger.debug('[AQM] No agent for email activity', { activityId });
      return null;
    }

    // Build email text from activity data
    const meta = activity.metadata as Record<string, any> | null;
    const emailText = [
      `Subject: ${activity.title}`,
      meta?.from ? `From: ${meta.from}` : '',
      meta?.to ? `To: ${meta.to}` : '',
      '',
      activity.description,
    ]
      .filter(Boolean)
      .join('\n');

    const evaluation = await runAiEvaluation(emailText, 'email');
    await storeEvaluation(evaluation, activity.performedById);

    logger.info('[AQM] Email auto-evaluated', {
      activityId,
      agentId: activity.performedById,
      percentage: evaluation.percentage,
    });

    return evaluation;
  } catch (error) {
    logger.error('[AQM] Failed to auto-evaluate email', {
      activityId,
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

// ---------------------------------------------------------------------------
// Evaluation Report
// ---------------------------------------------------------------------------

/**
 * Generate an aggregate evaluation report for a specific agent over a period.
 * Shows average scores per criterion, trend over time, and top strengths/improvements.
 *
 * @param agentId - The agent user ID
 * @param period - Date range for the report
 * @returns Comprehensive evaluation report
 */
export async function generateEvaluationReport(
  agentId: string,
  period: { start: Date; end: Date },
): Promise<EvaluationReport> {
  try {
    const agent = await prisma.user.findUnique({
      where: { id: agentId },
      select: { name: true },
    });

    const qaScores = await prisma.crmQaScore.findMany({
      where: {
        agentId,
        createdAt: { gte: period.start, lte: period.end },
        scores: {
          path: ['autoGenerated'],
          equals: true,
        },
      },
      select: {
        scores: true,
        totalScore: true,
        maxScore: true,
        percentage: true,
        createdAt: true,
      },
      orderBy: { createdAt: 'asc' },
    });

    // Aggregate criteria averages
    const criteria = getAutoEvaluationCriteria();
    const criteriaAverages: Record<string, number> = {};
    const criteriaSum: Record<string, number> = {};
    const criteriaCount: Record<string, number> = {};
    const allStrengths: Record<string, number> = {};
    const allImprovements: Record<string, number> = {};
    let complianceIssueCount = 0;

    for (const criterion of criteria) {
      criteriaSum[criterion.name] = 0;
      criteriaCount[criterion.name] = 0;
    }

    for (const score of qaScores) {
      const scoreData = score.scores as Record<string, any> | null;
      if (!scoreData) continue;

      for (const criterion of criteria) {
        const val = Number(scoreData[criterion.name]);
        if (!isNaN(val)) {
          criteriaSum[criterion.name] += val;
          criteriaCount[criterion.name]++;
        }
      }

      // Collect strengths and improvements
      if (Array.isArray(scoreData.strengths)) {
        for (const s of scoreData.strengths) {
          allStrengths[s] = (allStrengths[s] || 0) + 1;
        }
      }
      if (Array.isArray(scoreData.improvements)) {
        for (const i of scoreData.improvements) {
          allImprovements[i] = (allImprovements[i] || 0) + 1;
        }
      }
      if (Array.isArray(scoreData.complianceFlags) && scoreData.complianceFlags.length > 0) {
        complianceIssueCount += scoreData.complianceFlags.length;
      }
    }

    for (const criterion of criteria) {
      const count = criteriaCount[criterion.name];
      criteriaAverages[criterion.name] = count > 0
        ? Math.round((criteriaSum[criterion.name] / count) * 100) / 100
        : 0;
    }

    // Build daily trend
    const dayMap = new Map<string, { sum: number; count: number }>();
    for (const score of qaScores) {
      const dateKey = score.createdAt.toISOString().split('T')[0];
      const entry = dayMap.get(dateKey) || { sum: 0, count: 0 };
      entry.sum += Number(score.percentage);
      entry.count++;
      dayMap.set(dateKey, entry);
    }

    const trend = Array.from(dayMap.entries())
      .map(([date, entry]) => ({
        date,
        avgScore: Math.round((entry.sum / entry.count) * 100) / 100,
      }))
      .sort((a, b) => a.date.localeCompare(b.date));

    // Top strengths and improvements by frequency
    const topStrengths = Object.entries(allStrengths)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([s]) => s);

    const topImprovements = Object.entries(allImprovements)
      .sort(([, a], [, b]) => b - a)
      .slice(0, 5)
      .map(([s]) => s);

    // Average percentage
    const avgPercentage = qaScores.length > 0
      ? Math.round(
          (qaScores.reduce((s, q) => s + Number(q.percentage), 0) / qaScores.length) * 100,
        ) / 100
      : 0;

    const report: EvaluationReport = {
      agentId,
      agentName: agent?.name || 'Unknown',
      period,
      totalEvaluations: qaScores.length,
      avgPercentage,
      criteriaAverages,
      trend,
      topStrengths,
      topImprovements,
      complianceIssueCount,
    };

    logger.info('[AQM] Report generated', {
      agentId,
      totalEvaluations: qaScores.length,
      avgPercentage,
    });

    return report;
  } catch (error) {
    logger.error('[AQM] Failed to generate report', {
      agentId,
      error: error instanceof Error ? error.message : String(error),
    });

    return {
      agentId,
      agentName: 'Unknown',
      period,
      totalEvaluations: 0,
      avgPercentage: 0,
      criteriaAverages: {},
      trend: [],
      topStrengths: [],
      topImprovements: [],
      complianceIssueCount: 0,
    };
  }
}

// ---------------------------------------------------------------------------
// Calibration
// ---------------------------------------------------------------------------

/**
 * Compare an AI auto-score against a human QA score for calibration.
 * Measures agreement between AI and human evaluators to track AI accuracy.
 *
 * @param autoScoreId - The CrmQaScore ID of the auto-generated evaluation
 * @param humanScores - Human evaluator scores keyed by criterion name
 * @returns Calibration result with per-criterion comparison
 */
export async function calibrateWithHumanScores(
  autoScoreId: string,
  humanScores: Record<string, number>,
): Promise<CalibrationResult | null> {
  try {
    const autoScore = await prisma.crmQaScore.findUnique({
      where: { id: autoScoreId },
      select: { scores: true },
    });

    if (!autoScore?.scores) {
      logger.warn('[AQM] Auto-score not found for calibration', { autoScoreId });
      return null;
    }

    const autoScoreData = autoScore.scores as Record<string, any>;
    const criteria = getAutoEvaluationCriteria();
    const criteriaComparison: CalibrationResult['criteriaComparison'] = [];
    let totalDifference = 0;
    let comparedCount = 0;

    for (const criterion of criteria) {
      const autoVal = Number(autoScoreData[criterion.name]) || 0;
      const humanVal = Number(humanScores[criterion.name]) || 0;

      if (humanScores[criterion.name] !== undefined) {
        const difference = Math.abs(autoVal - humanVal);
        criteriaComparison.push({
          criterion: criterion.name,
          autoScore: autoVal,
          humanScore: humanVal,
          difference,
        });
        totalDifference += difference;
        comparedCount++;
      }
    }

    // Agreement = 1 - (average difference / max possible difference)
    const avgDifference = comparedCount > 0 ? totalDifference / comparedCount : 0;
    const agreement = Math.round((1 - avgDifference / 4) * 100) / 100; // Max diff is 4 (5-1)

    const overallAgreement: CalibrationResult['overallAgreement'] =
      agreement >= 0.9 ? 'EXCELLENT'
        : agreement >= 0.75 ? 'GOOD'
          : agreement >= 0.5 ? 'FAIR'
            : 'POOR';

    const result: CalibrationResult = {
      autoScoreId,
      agreement,
      criteriaComparison,
      overallAgreement,
    };

    // Store calibration data in the auto-score metadata
    await prisma.crmQaScore.update({
      where: { id: autoScoreId },
      data: {
        scores: {
          ...autoScoreData,
          calibration: {
            humanScores,
            agreement,
            overallAgreement,
            calibratedAt: new Date().toISOString(),
          },
        } as unknown as Prisma.InputJsonValue,
      },
    });

    logger.info('[AQM] Calibration completed', {
      autoScoreId,
      agreement,
      overallAgreement,
    });

    return result;
  } catch (error) {
    logger.error('[AQM] Calibration failed', {
      autoScoreId,
      error: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}
