export const dynamic = 'force-dynamic';

/**
 * POST /api/lms/tutor/tts — Text-to-Speech for Aurelia Tutor
 * =============================================================================
 * Accepts a JSON body { text, voiceId? } and returns an audio/mpeg stream
 * generated by the ElevenLabs v1 text-to-speech API.
 *
 * Body: { text: string, voiceId?: string }
 *
 * Auth: Required (withUserGuard)
 * Rate limit: 10 req/min (TTS generation is resource-intensive)
 * CSRF: Required (POST mutation)
 *
 * Returns: audio/mpeg stream on success, JSON error on failure.
 */

import { NextRequest, NextResponse } from 'next/server';
import { withUserGuard } from '@/lib/user-api-guard';
import { logger } from '@/lib/logger';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const ELEVENLABS_API_BASE = 'https://api.elevenlabs.io/v1';

/** Maximum text length allowed per request */
const MAX_TEXT_LENGTH = 5000;

/** ElevenLabs model optimized for multilingual + low latency */
const DEFAULT_MODEL_ID = 'eleven_multilingual_v2';

/** Voice settings for a warm, professional tutor tone */
const VOICE_SETTINGS = {
  stability: 0.65,
  similarity_boost: 0.75,
  style: 0.35,
  use_speaker_boost: true,
};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface TtsRequestBody {
  text: string;
  voiceId?: string;
}

// ---------------------------------------------------------------------------
// Route Handler
// ---------------------------------------------------------------------------

export const POST = withUserGuard(async (request: NextRequest) => {
  // Verify ElevenLabs API key is configured
  const apiKey = process.env.ELEVENLABS_API_KEY;
  if (!apiKey) {
    logger.error('[TTS] ELEVENLABS_API_KEY not configured');
    return NextResponse.json(
      { error: 'Service de synthèse vocale non configuré.' },
      { status: 503 }
    );
  }

  // Parse request body
  let body: TtsRequestBody;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json(
      { error: 'Corps de requête JSON invalide.' },
      { status: 400 }
    );
  }

  const { text, voiceId } = body;

  // Validate text
  if (!text || typeof text !== 'string') {
    return NextResponse.json(
      { error: 'Le champ "text" est requis et doit être une chaîne de caractères.' },
      { status: 400 }
    );
  }

  const trimmedText = text.trim();

  if (trimmedText.length === 0) {
    return NextResponse.json(
      { error: 'Le texte est vide.' },
      { status: 400 }
    );
  }

  if (trimmedText.length > MAX_TEXT_LENGTH) {
    return NextResponse.json(
      { error: `Le texte dépasse la limite de ${MAX_TEXT_LENGTH} caractères (${trimmedText.length} fournis).` },
      { status: 400 }
    );
  }

  // Resolve voice ID: parameter > env > error
  const resolvedVoiceId = voiceId || process.env.ELEVENLABS_VOICE_ID;
  if (!resolvedVoiceId) {
    logger.error('[TTS] No voice ID provided and ELEVENLABS_VOICE_ID not configured');
    return NextResponse.json(
      { error: 'Aucun identifiant de voix configuré.' },
      { status: 503 }
    );
  }

  try {
    // Call ElevenLabs TTS API
    const elevenLabsUrl = `${ELEVENLABS_API_BASE}/text-to-speech/${resolvedVoiceId}`;

    // FIX P4-09: AbortController with 15s timeout to prevent hanging requests
    const ttsAbort = new AbortController();
    const ttsTimeout = setTimeout(() => ttsAbort.abort(), 15_000);

    let ttsResponse: Response;
    try {
      ttsResponse = await fetch(elevenLabsUrl, {
        method: 'POST',
        headers: {
          'xi-api-key': apiKey,
          'Content-Type': 'application/json',
          'Accept': 'audio/mpeg',
        },
        body: JSON.stringify({
          text: trimmedText,
          model_id: DEFAULT_MODEL_ID,
          voice_settings: VOICE_SETTINGS,
        }),
        signal: ttsAbort.signal,
      });
    } finally {
      clearTimeout(ttsTimeout);
    }

    if (!ttsResponse.ok) {
      const errorBody = await ttsResponse.text().catch(() => 'Unknown error');
      logger.error('[TTS] ElevenLabs API error', {
        status: ttsResponse.status,
        body: errorBody.slice(0, 500),
      });

      if (ttsResponse.status === 401) {
        return NextResponse.json(
          { error: 'Clé API ElevenLabs invalide.' },
          { status: 503 }
        );
      }

      if (ttsResponse.status === 429) {
        return NextResponse.json(
          { error: 'Limite de requêtes ElevenLabs atteinte. Réessayez dans quelques instants.' },
          { status: 429 }
        );
      }

      if (ttsResponse.status === 422) {
        return NextResponse.json(
          { error: 'Texte ou paramètres invalides pour la synthèse vocale.' },
          { status: 400 }
        );
      }

      return NextResponse.json(
        { error: 'Erreur lors de la synthèse vocale. Réessayez.' },
        { status: 502 }
      );
    }

    // Stream the audio response back to the client
    const audioBuffer = await ttsResponse.arrayBuffer();

    return new NextResponse(audioBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'audio/mpeg',
        'Content-Length': String(audioBuffer.byteLength),
        'Cache-Control': 'private, max-age=3600', // Cache for 1 hour
      },
    });
  } catch (error) {
    // FIX P4-09: Distinguish timeout from other errors
    if (error instanceof Error && error.name === 'AbortError') {
      logger.error('[TTS] ElevenLabs request timed out (15s)');
      return NextResponse.json(
        { error: 'Le service de synthèse vocale a expiré. Réessayez.' },
        { status: 504 }
      );
    }

    logger.error('[TTS] Text-to-speech failed', {
      error: error instanceof Error ? error.message : String(error),
    });

    return NextResponse.json(
      { error: 'Erreur interne lors de la synthèse vocale.' },
      { status: 500 }
    );
  }
}, { rateLimit: 10 });
