export const dynamic = 'force-dynamic';

/**
 * Shared Cart Resolution API
 * GET /api/cart/shared/[code]
 *
 * The [code] parameter is the JWT token generated by POST /api/cart/share.
 * This endpoint decodes the token and returns items enriched with CURRENT
 * product prices and availability - not the prices at share time.
 *
 * This allows URL-based sharing: /cart?share=<token>
 * The CartShareBanner component reads the `share` query param and calls this
 * endpoint to resolve the items before offering to add them to the cart.
 */

import { NextRequest, NextResponse } from 'next/server';
import { jwtVerify } from 'jose';
import { prisma } from '@/lib/db';
import { logger } from '@/lib/logger';
import { rateLimitMiddleware } from '@/lib/rate-limiter';
import { getClientIpFromRequest } from '@/lib/admin-audit';

// COMMERCE-010 FIX: Must match the secret used in /api/cart/share (CART_SHARE_SECRET)
// Lazy-initialized to avoid crashing during Next.js build/SSG when env vars
// are not available (see KB-PP-BUILD-002).
let _shareSecret: Uint8Array | null = null;
function getShareSecret(): Uint8Array {
  if (!_shareSecret) {
    const dedicatedSecret = process.env.CART_SHARE_SECRET;
    if (dedicatedSecret) {
      _shareSecret = new TextEncoder().encode(dedicatedSecret);
    } else {
      if (!process.env.NEXTAUTH_SECRET) {
        throw new Error('CART_SHARE_SECRET or NEXTAUTH_SECRET environment variable is required for cart sharing');
      }
      _shareSecret = new TextEncoder().encode(`cart-share:${process.env.NEXTAUTH_SECRET}`);
    }
  }
  return _shareSecret;
}

interface SharedCartItem {
  productId: string;
  optionId?: string | null;
  name: string;
  price: number;
  quantity: number;
  image?: string | null;
}

interface SharedCartPayload {
  items: SharedCartItem[];
}

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ code: string }> }
) {
  try {
    // COMMERCE-022 FIX: Rate limiting on public shared cart endpoint
    const ip = getClientIpFromRequest(_request);
    const rl = await rateLimitMiddleware(ip, '/api/cart/shared');
    if (!rl.success) {
      const res = NextResponse.json({ error: 'Too many requests' }, { status: 429 });
      Object.entries(rl.headers).forEach(([k, v]) => res.headers.set(k, v));
      return res;
    }

    const { code } = await params;

    if (!code) {
      return NextResponse.json({ error: 'Missing share code' }, { status: 400 });
    }

    // The "code" is the JWT token - decode it
    let payload: SharedCartPayload;
    try {
      const { payload: decoded } = await jwtVerify(code, getShareSecret());
      payload = (decoded as { cart: SharedCartPayload }).cart;
    } catch {
      return NextResponse.json(
        { error: 'Invalid or expired share link' },
        { status: 400 }
      );
    }

    if (!payload?.items || !Array.isArray(payload.items) || payload.items.length === 0) {
      return NextResponse.json({ error: 'No items in shared cart' }, { status: 400 });
    }

    // Collect all product IDs and format IDs we need to verify
    const productIds = [...new Set(payload.items.map((i) => i.productId))];
    const optionIds = payload.items
      .map((i) => i.optionId)
      .filter((id): id is string => !!id);

    // Fetch current product data with active options
    const products = await prisma.product.findMany({
      where: { id: { in: productIds }, isActive: true },
      select: {
        id: true,
        name: true,
        price: true,
        imageUrl: true,
        stockQuantity: true,
        images: {
          select: { url: true },
          orderBy: { sortOrder: 'asc' },
          take: 1,
        },
        options: {
          where: optionIds.length > 0 ? { id: { in: optionIds } } : { isActive: true },
          select: {
            id: true,
            name: true,
            price: true,
            stockQuantity: true,
            isActive: true,
          },
        },
      },
    });

    const productMap = new Map(products.map((p) => [p.id, p]));

    // Resolve items with current prices and availability
    const resolvedItems = payload.items.map((sharedItem) => {
      const product = productMap.get(sharedItem.productId);

      // Product no longer exists or is inactive
      if (!product) {
        return {
          productId: sharedItem.productId,
          optionId: sharedItem.optionId ?? null,
          name: sharedItem.name,
          quantity: sharedItem.quantity,
          currentPrice: null,
          image: sharedItem.image ?? null,
          available: false,
          unavailableReason: 'product_unavailable',
        };
      }

      // Resolve format if specified
      let currentPrice: number;
      let inStock: boolean;
      let optionName: string | undefined;

      if (sharedItem.optionId) {
        const format = product.options.find((f) => f.id === sharedItem.optionId);
        if (!format) {
          // Format was removed - fall back to base product price
          currentPrice = Number(product.price);
          inStock = (product.stockQuantity ?? 0) > 0;
        } else {
          currentPrice = format.price ? Number(format.price) : Number(product.price);
          inStock = (format.stockQuantity ?? product.stockQuantity ?? 0) > 0;
          optionName = format.name;
        }
      } else {
        currentPrice = Number(product.price);
        inStock = (product.stockQuantity ?? 0) > 0;
      }

      // Resolve image
      const imageUrl =
        product.imageUrl ||
        (product.images.length > 0 ? product.images[0].url : null);

      return {
        productId: sharedItem.productId,
        optionId: sharedItem.optionId ?? null,
        name: product.name,
        optionName: optionName ?? null,
        quantity: sharedItem.quantity,
        currentPrice,
        image: imageUrl,
        available: inStock,
        unavailableReason: inStock ? null : 'out_of_stock',
      };
    });

    const availableCount = resolvedItems.filter((i) => i.available).length;

    return NextResponse.json({
      success: true,
      items: resolvedItems,
      itemCount: resolvedItems.reduce((sum, i) => sum + i.quantity, 0),
      availableCount,
    });
  } catch (error) {
    logger.error('Shared cart resolution failed', {
      error: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
