/**
 * PDF Reports Service
 * Generates PDF reports for financial statements and tax reports
 */

import { TaxReport, JournalEntry } from './types';

// i18n labels for PDF reports
type PdfLocale = 'fr' | 'en';

const PDF_LABELS: Record<PdfLocale, Record<string, string>> = {
  fr: {
    taxReportTitle: 'RAPPORT DE TAXES TPS/TVQ',
    period: 'Période',
    companyInfo: "INFORMATIONS DE L'ENTREPRISE",
    businessName: 'Raison sociale',
    address: 'Adresse',
    city: 'Ville',
    declarationPeriod: 'PÉRIODE DE DÉCLARATION',
    type: 'Type',
    year: 'Année',
    dueDate: 'Date limite',
    status: 'Statut',
    monthly: 'Mensuelle',
    quarterly: 'Trimestrielle',
    annual: 'Annuelle',
    salesAndTaxes: 'VENTES ET TAXES PERÇUES',
    description: 'Description',
    amount: 'Montant',
    totalSales: 'Ventes totales',
    transactions: 'transactions',
    tpsCollected: 'TPS perçue (5%)',
    tvqCollected: 'TVQ perçue (9.975%)',
    totalTaxCollected: 'Total taxes perçues',
    inputTaxCredits: 'CRÉDITS DE TAXE SUR INTRANTS (CTI/RTI)',
    tpsPaidCti: 'TPS payée sur achats (CTI)',
    tvqPaidRti: 'TVQ payée sur achats (RTI)',
    totalCredits: 'Total crédits réclamés',
    remittanceSummary: 'RÉSUMÉ - MONTANTS À REMETTRE',
    netTps: 'TPS nette (perçue - CTI)',
    netTvq: 'TVQ nette (perçue - RTI)',
    totalRemit: 'TOTAL À REMETTRE',
    generatedBy: 'Ce document a été généré automatiquement par le système comptable',
    generationDate: 'Date de génération',
    contactInfo: 'Pour toute question, contactez votre comptable ou Revenu Québec.',
    // Income statement
    incomeStatementTitle: 'ÉTAT DES RÉSULTATS',
    revenue: 'REVENUS',
    totalRevenue: 'Total revenus',
    cogs: 'COÛT DES MARCHANDISES VENDUES',
    totalCogs: 'Total CMV',
    grossProfit: 'MARGE BRUTE',
    operatingExpenses: "DÉPENSES D'EXPLOITATION",
    totalExpenses: 'Total dépenses',
    operatingProfit: "BÉNÉFICE D'EXPLOITATION",
    otherIncomeExpenses: 'AUTRES PRODUITS / CHARGES',
    netProfit: 'BÉNÉFICE NET',
    generatedOn: 'Document généré le',
    // Balance sheet
    balanceSheetTitle: 'BILAN',
    asOf: 'Au',
    assets: 'ACTIFS',
    currentAssets: 'Actifs courants',
    totalCurrentAssets: 'Total actifs courants',
    nonCurrentAssets: 'Actifs non courants',
    totalNonCurrentAssets: 'Total actifs non courants',
    totalAssets: 'TOTAL ACTIFS',
    liabilitiesAndEquity: 'PASSIFS & CAPITAUX PROPRES',
    currentLiabilities: 'Passifs courants',
    totalLiabilities: 'Total passifs',
    equity: 'Capitaux propres',
    totalEquity: 'Total capitaux propres',
    totalLiabilitiesEquity: 'TOTAL PASSIFS & CAPITAUX',
    // Journal entry
    journalEntryTitle: 'ÉCRITURE DE JOURNAL',
    entryNumber: 'N° Écriture',
    date: 'Date',
    reference: 'Référence',
    account: 'Compte',
    debit: 'Débit',
    credit: 'Crédit',
    total: 'TOTAL',
    createdBy: 'Créé par',
  },
  en: {
    taxReportTitle: 'GST/QST TAX REPORT',
    period: 'Period',
    companyInfo: 'COMPANY INFORMATION',
    businessName: 'Business name',
    address: 'Address',
    city: 'City',
    declarationPeriod: 'REPORTING PERIOD',
    type: 'Type',
    year: 'Year',
    dueDate: 'Due date',
    status: 'Status',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    annual: 'Annual',
    salesAndTaxes: 'SALES AND TAXES COLLECTED',
    description: 'Description',
    amount: 'Amount',
    totalSales: 'Total sales',
    transactions: 'transactions',
    tpsCollected: 'GST collected (5%)',
    tvqCollected: 'QST collected (9.975%)',
    totalTaxCollected: 'Total taxes collected',
    inputTaxCredits: 'INPUT TAX CREDITS (ITC/ITR)',
    tpsPaidCti: 'GST paid on purchases (ITC)',
    tvqPaidRti: 'QST paid on purchases (ITR)',
    totalCredits: 'Total credits claimed',
    remittanceSummary: 'SUMMARY - AMOUNTS TO REMIT',
    netTps: 'Net GST (collected - ITC)',
    netTvq: 'Net QST (collected - ITR)',
    totalRemit: 'TOTAL TO REMIT',
    generatedBy: 'This document was automatically generated by the accounting system',
    generationDate: 'Generation date',
    contactInfo: 'For any questions, contact your accountant or Revenu Québec.',
    incomeStatementTitle: 'INCOME STATEMENT',
    revenue: 'REVENUE',
    totalRevenue: 'Total revenue',
    cogs: 'COST OF GOODS SOLD',
    totalCogs: 'Total COGS',
    grossProfit: 'GROSS PROFIT',
    operatingExpenses: 'OPERATING EXPENSES',
    totalExpenses: 'Total expenses',
    operatingProfit: 'OPERATING PROFIT',
    otherIncomeExpenses: 'OTHER INCOME / EXPENSES',
    netProfit: 'NET PROFIT',
    generatedOn: 'Document generated on',
    balanceSheetTitle: 'BALANCE SHEET',
    asOf: 'As of',
    assets: 'ASSETS',
    currentAssets: 'Current assets',
    totalCurrentAssets: 'Total current assets',
    nonCurrentAssets: 'Non-current assets',
    totalNonCurrentAssets: 'Total non-current assets',
    totalAssets: 'TOTAL ASSETS',
    liabilitiesAndEquity: 'LIABILITIES & EQUITY',
    currentLiabilities: 'Current liabilities',
    totalLiabilities: 'Total liabilities',
    equity: 'Equity',
    totalEquity: 'Total equity',
    totalLiabilitiesEquity: 'TOTAL LIABILITIES & EQUITY',
    journalEntryTitle: 'JOURNAL ENTRY',
    entryNumber: 'Entry #',
    date: 'Date',
    reference: 'Reference',
    account: 'Account',
    debit: 'Debit',
    credit: 'Credit',
    total: 'TOTAL',
    createdBy: 'Created by',
  },
};

function getLabels(locale?: string): Record<string, string> {
  const lang = (locale === 'en' ? 'en' : 'fr') as PdfLocale;
  return PDF_LABELS[lang];
}

function formatLocale(locale?: string): string {
  return locale === 'en' ? 'en-CA' : 'fr-CA';
}

interface CompanyInfo {
  name: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  phone: string;
  email: string;
  tpsNumber: string;
  tvqNumber: string;
  neq: string;
}

const DEFAULT_COMPANY: CompanyInfo = {
  name: process.env.BUSINESS_NAME || 'BioCycle Peptides Inc.',
  address: process.env.BUSINESS_STREET || '',
  city: process.env.BUSINESS_CITY || 'Montréal',
  province: process.env.BUSINESS_PROVINCE || 'QC',
  postalCode: process.env.BUSINESS_POSTAL_CODE || '',
  phone: process.env.BUSINESS_PHONE || '',
  email: process.env.NEXT_PUBLIC_INFO_EMAIL || 'info@biocyclepeptides.com',
  tpsNumber: process.env.TPS_NUMBER || '',
  tvqNumber: process.env.TVQ_NUMBER || '',
  neq: process.env.NEQ_NUMBER || '',
};

/**
 * Generate HTML for TPS/TVQ tax report (FPZ-500 style)
 */
export function generateTaxReportHTML(report: TaxReport, company: CompanyInfo = DEFAULT_COMPANY, locale?: string): string {
  const L = getLabels(locale);
  const fmt = formatLocale(locale);
  const netTps = report.tpsCollected - report.tpsPaid;
  const netTvq = report.tvqCollected - report.tvqPaid;
  const totalRemittance = netTps + netTvq;

  return `
<!DOCTYPE html>
<html lang="${locale === 'en' ? 'en' : 'fr'}">
<head>
  <meta charset="UTF-8">
  <title>${L.taxReportTitle} - ${report.period}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #333; padding: 40px; }
    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #1a5f7a; padding-bottom: 20px; }
    .header h1 { font-size: 18px; color: #1a5f7a; margin-bottom: 5px; }
    .header h2 { font-size: 14px; color: #666; font-weight: normal; }
    .company-info { display: flex; justify-content: space-between; margin-bottom: 30px; }
    .company-box, .period-box { background: #f8f9fa; padding: 15px; border-radius: 4px; width: 48%; }
    .company-box h3, .period-box h3 { font-size: 12px; color: #1a5f7a; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px; }
    .info-row { display: flex; margin-bottom: 5px; }
    .info-label { width: 120px; color: #666; }
    .info-value { font-weight: bold; }
    .section { margin-bottom: 25px; }
    .section-title { background: #1a5f7a; color: white; padding: 8px 15px; font-size: 12px; font-weight: bold; margin-bottom: 1px; }
    table { width: 100%; border-collapse: collapse; }
    th, td { padding: 10px 15px; text-align: left; border-bottom: 1px solid #eee; }
    th { background: #f0f0f0; font-weight: bold; color: #333; }
    td.amount { text-align: right; font-family: 'Courier New', monospace; }
    tr.total { background: #e8f4f8; font-weight: bold; }
    tr.total td { border-top: 2px solid #1a5f7a; }
    .summary-box { background: #1a5f7a; color: white; padding: 20px; border-radius: 4px; margin-top: 20px; }
    .summary-box h3 { font-size: 14px; margin-bottom: 15px; }
    .summary-row { display: flex; justify-content: space-between; margin-bottom: 8px; }
    .summary-total { font-size: 18px; border-top: 1px solid rgba(255,255,255,0.3); padding-top: 10px; margin-top: 10px; }
    .footer { margin-top: 40px; text-align: center; color: #666; font-size: 10px; border-top: 1px solid #ddd; padding-top: 20px; }
    .status-badge { display: inline-block; padding: 3px 10px; border-radius: 3px; font-size: 10px; font-weight: bold; }
    .status-generated { background: #e3f2fd; color: #1565c0; }
    .status-filed { background: #fff3e0; color: #ef6c00; }
    .status-paid { background: #e8f5e9; color: #2e7d32; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${L.taxReportTitle}</h1>
    <h2>${L.period}: ${report.period}</h2>
  </div>

  <div class="company-info">
    <div class="company-box">
      <h3>${L.companyInfo}</h3>
      <div class="info-row"><span class="info-label">${L.businessName}:</span><span class="info-value">${company.name}</span></div>
      <div class="info-row"><span class="info-label">${L.address}:</span><span class="info-value">${company.address}</span></div>
      <div class="info-row"><span class="info-label">${L.city}:</span><span class="info-value">${company.city}, ${company.province} ${company.postalCode}</span></div>
      <div class="info-row"><span class="info-label">N° TPS/GST:</span><span class="info-value">${company.tpsNumber}</span></div>
      <div class="info-row"><span class="info-label">N° TVQ/QST:</span><span class="info-value">${company.tvqNumber}</span></div>
    </div>
    <div class="period-box">
      <h3>${L.declarationPeriod}</h3>
      <div class="info-row"><span class="info-label">${L.type}:</span><span class="info-value">${report.periodType === 'MONTHLY' ? L.monthly : report.periodType === 'QUARTERLY' ? L.quarterly : L.annual}</span></div>
      <div class="info-row"><span class="info-label">${L.year}:</span><span class="info-value">${report.year}</span></div>
      <div class="info-row"><span class="info-label">${L.period}:</span><span class="info-value">${report.period}</span></div>
      <div class="info-row"><span class="info-label">${L.dueDate}:</span><span class="info-value">${new Date(report.dueDate).toLocaleDateString(fmt)}</span></div>
      <div class="info-row"><span class="info-label">${L.status}:</span><span class="status-badge status-${report.status.toLowerCase()}">${report.status}</span></div>
    </div>
  </div>

  <div class="section">
    <div class="section-title">${L.salesAndTaxes}</div>
    <table>
      <tr>
        <th>${L.description}</th>
        <th style="text-align: right;">${L.amount}</th>
      </tr>
      <tr>
        <td>${L.totalSales} (${report.salesCount} ${L.transactions})</td>
        <td class="amount">${report.totalSales.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
      <tr>
        <td>${L.tpsCollected}</td>
        <td class="amount">${report.tpsCollected.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
      <tr>
        <td>${L.tvqCollected}</td>
        <td class="amount">${report.tvqCollected.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
      <tr class="total">
        <td>${L.totalTaxCollected}</td>
        <td class="amount">${(report.tpsCollected + report.tvqCollected).toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
    </table>
  </div>

  <div class="section">
    <div class="section-title">${L.inputTaxCredits}</div>
    <table>
      <tr>
        <th>${L.description}</th>
        <th style="text-align: right;">${L.amount}</th>
      </tr>
      <tr>
        <td>${L.tpsPaidCti}</td>
        <td class="amount">${report.tpsPaid.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
      <tr>
        <td>${L.tvqPaidRti}</td>
        <td class="amount">${report.tvqPaid.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
      <tr class="total">
        <td>${L.totalCredits}</td>
        <td class="amount">${(report.tpsPaid + report.tvqPaid).toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
    </table>
  </div>

  <div class="summary-box">
    <h3>${L.remittanceSummary}</h3>
    <div class="summary-row">
      <span>${L.netTps}</span>
      <span>${netTps.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</span>
    </div>
    <div class="summary-row">
      <span>${L.netTvq}</span>
      <span>${netTvq.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</span>
    </div>
    <div class="summary-row summary-total">
      <span>${L.totalRemit}</span>
      <span style="font-size: 20px;">${totalRemittance.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</span>
    </div>
  </div>

  <div class="footer">
    <p>${L.generatedBy} ${company.name}.</p>
    <p>${L.generationDate}: ${new Date().toLocaleDateString(fmt)} ${new Date().toLocaleTimeString(fmt)}</p>
    <p>${L.contactInfo}</p>
  </div>
</body>
</html>
  `;
}

/**
 * Generate HTML for Income Statement
 */
export function generateIncomeStatementHTML(
  data: {
    revenue: Record<string, number>;
    cogs: Record<string, number>;
    expenses: Record<string, number>;
    other: Record<string, number>;
  },
  period: string,
  company: CompanyInfo = DEFAULT_COMPANY,
  locale?: string
): string {
  const L = getLabels(locale);
  const fmt = formatLocale(locale);
  const totalRevenue = Object.values(data.revenue).reduce((a, b) => a + b, 0);
  const totalCogs = Object.values(data.cogs).reduce((a, b) => a + b, 0);
  const grossProfit = totalRevenue - totalCogs;
  const totalExpenses = Object.values(data.expenses).reduce((a, b) => a + b, 0);
  const operatingProfit = grossProfit - totalExpenses;
  const totalOther = Object.values(data.other).reduce((a, b) => a + b, 0);
  const netProfit = operatingProfit + totalOther;

  const revenueLabels: Record<string, string> = {
    salesCanada: 'Ventes Canada',
    salesUSA: 'Ventes USA',
    salesEurope: 'Ventes Europe',
    salesOther: 'Ventes autres pays',
    shippingCharged: 'Frais de livraison facturés',
    discounts: 'Remises et retours',
  };

  const cogsLabels: Record<string, string> = {
    purchases: 'Achats de marchandises',
    customs: 'Frais de douane et importation',
    inboundShipping: 'Frais de transport entrant',
  };

  const expenseLabels: Record<string, string> = {
    shipping: 'Frais de livraison',
    paymentFees: 'Frais bancaires et paiement',
    marketing: 'Marketing et publicité',
    hosting: 'Hébergement et tech',
    professional: 'Frais professionnels',
    depreciation: 'Amortissement',
  };

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${L.incomeStatementTitle} - ${period}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #333; padding: 40px; }
    .header { text-align: center; margin-bottom: 30px; }
    .header h1 { font-size: 18px; color: #1a5f7a; margin-bottom: 5px; }
    .header h2 { font-size: 14px; color: #666; font-weight: normal; }
    .header h3 { font-size: 12px; color: #888; font-weight: normal; margin-top: 5px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th, td { padding: 8px 15px; text-align: left; }
    th { background: #1a5f7a; color: white; font-weight: bold; }
    td.amount { text-align: right; font-family: 'Courier New', monospace; }
    td.indent { padding-left: 30px; }
    tr.subtotal { background: #f0f0f0; font-weight: bold; }
    tr.total { background: #1a5f7a; color: white; font-weight: bold; }
    tr.section-header td { background: #e8f4f8; font-weight: bold; color: #1a5f7a; padding-top: 15px; }
    .negative { color: #c62828; }
    .positive { color: #2e7d32; }
    .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${company.name}</h1>
    <h2>${L.incomeStatementTitle}</h2>
    <h3>${L.period}: ${period}</h3>
  </div>

  <table>
    <tr class="section-header"><td colspan="2">${L.revenue}</td></tr>
    ${Object.entries(data.revenue).map(([key, value]) => `
      <tr>
        <td class="indent">${revenueLabels[key] || key}</td>
        <td class="amount ${value < 0 ? 'negative' : ''}">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
    `).join('')}
    <tr class="subtotal">
      <td>${L.totalRevenue}</td>
      <td class="amount">${totalRevenue.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
    </tr>

    <tr class="section-header"><td colspan="2">${L.cogs}</td></tr>
    ${Object.entries(data.cogs).map(([key, value]) => `
      <tr>
        <td class="indent">${cogsLabels[key] || key}</td>
        <td class="amount">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
    `).join('')}
    <tr class="subtotal">
      <td>${L.totalCogs}</td>
      <td class="amount">(${totalCogs.toLocaleString(fmt, { minimumFractionDigits: 2 })}) $</td>
    </tr>

    <tr class="subtotal" style="background: #d4edda;">
      <td>${L.grossProfit}</td>
      <td class="amount positive">${grossProfit.toLocaleString(fmt, { minimumFractionDigits: 2 })} $ (${((grossProfit/totalRevenue)*100).toFixed(1)}%)</td>
    </tr>

    <tr class="section-header"><td colspan="2">${L.operatingExpenses}</td></tr>
    ${Object.entries(data.expenses).map(([key, value]) => `
      <tr>
        <td class="indent">${expenseLabels[key] || key}</td>
        <td class="amount">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
      </tr>
    `).join('')}
    <tr class="subtotal">
      <td>${L.totalExpenses}</td>
      <td class="amount">(${totalExpenses.toLocaleString(fmt, { minimumFractionDigits: 2 })}) $</td>
    </tr>

    <tr class="subtotal" style="background: #e3f2fd;">
      <td>${L.operatingProfit}</td>
      <td class="amount">${operatingProfit.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
    </tr>

    ${Object.keys(data.other).length > 0 ? `
      <tr class="section-header"><td colspan="2">${L.otherIncomeExpenses}</td></tr>
      ${Object.entries(data.other).map(([key, value]) => `
        <tr>
          <td class="indent">${key}</td>
          <td class="amount ${value < 0 ? 'negative' : ''}">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
        </tr>
      `).join('')}
    ` : ''}

    <tr class="total">
      <td>${L.netProfit}</td>
      <td class="amount">${netProfit.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
    </tr>
  </table>

  <div class="footer">
    <p>${L.generatedOn} ${new Date().toLocaleDateString(fmt)}</p>
  </div>
</body>
</html>
  `;
}

/**
 * Generate HTML for Balance Sheet
 */
export function generateBalanceSheetHTML(
  data: {
    assets: { current: Record<string, number>; nonCurrent: Record<string, number> };
    liabilities: { current: Record<string, number> };
    equity: Record<string, number>;
  },
  asOfDate: string,
  company: CompanyInfo = DEFAULT_COMPANY,
  locale?: string
): string {
  const L = getLabels(locale);
  const fmt = formatLocale(locale);
  const totalCurrentAssets = Object.values(data.assets.current).reduce((a, b) => a + b, 0);
  const totalNonCurrentAssets = Object.values(data.assets.nonCurrent).reduce((a, b) => a + b, 0);
  const totalAssets = totalCurrentAssets + totalNonCurrentAssets;
  const totalLiabilities = Object.values(data.liabilities.current).reduce((a, b) => a + b, 0);
  const totalEquity = Object.values(data.equity).reduce((a, b) => a + b, 0);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${L.balanceSheetTitle} - ${asOfDate}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; color: #333; padding: 40px; }
    .header { text-align: center; margin-bottom: 30px; }
    .header h1 { font-size: 18px; color: #1a5f7a; margin-bottom: 5px; }
    .header h2 { font-size: 14px; color: #666; font-weight: normal; }
    .columns { display: flex; gap: 30px; }
    .column { flex: 1; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th, td { padding: 8px 12px; text-align: left; }
    th { background: #1a5f7a; color: white; font-weight: bold; }
    td.amount { text-align: right; font-family: 'Courier New', monospace; }
    td.indent { padding-left: 25px; }
    tr.subtotal { background: #f0f0f0; font-weight: bold; }
    tr.total { background: #1a5f7a; color: white; font-weight: bold; }
    .section-title { background: #e8f4f8; padding: 8px 12px; font-weight: bold; color: #1a5f7a; margin-top: 15px; }
    .negative { color: #c62828; }
    .footer { margin-top: 30px; text-align: center; color: #666; font-size: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${company.name}</h1>
    <h2>${L.balanceSheetTitle}</h2>
    <h3>${L.asOf} ${asOfDate}</h3>
  </div>

  <div class="columns">
    <div class="column">
      <table>
        <tr><th colspan="2">${L.assets}</th></tr>
        <tr><td colspan="2" class="section-title">${L.currentAssets}</td></tr>
        ${Object.entries(data.assets.current).map(([key, value]) => `
          <tr>
            <td class="indent">${key}</td>
            <td class="amount ${value < 0 ? 'negative' : ''}">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
          </tr>
        `).join('')}
        <tr class="subtotal">
          <td>${L.totalCurrentAssets}</td>
          <td class="amount">${totalCurrentAssets.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
        </tr>

        <tr><td colspan="2" class="section-title">${L.nonCurrentAssets}</td></tr>
        ${Object.entries(data.assets.nonCurrent).map(([key, value]) => `
          <tr>
            <td class="indent">${key}</td>
            <td class="amount ${value < 0 ? 'negative' : ''}">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
          </tr>
        `).join('')}
        <tr class="subtotal">
          <td>${L.totalNonCurrentAssets}</td>
          <td class="amount">${totalNonCurrentAssets.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
        </tr>

        <tr class="total">
          <td>${L.totalAssets}</td>
          <td class="amount">${totalAssets.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
        </tr>
      </table>
    </div>

    <div class="column">
      <table>
        <tr><th colspan="2">${L.liabilitiesAndEquity}</th></tr>
        <tr><td colspan="2" class="section-title">${L.currentLiabilities}</td></tr>
        ${Object.entries(data.liabilities.current).map(([key, value]) => `
          <tr>
            <td class="indent">${key}</td>
            <td class="amount">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
          </tr>
        `).join('')}
        <tr class="subtotal">
          <td>${L.totalLiabilities}</td>
          <td class="amount">${totalLiabilities.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
        </tr>

        <tr><td colspan="2" class="section-title">${L.equity}</td></tr>
        ${Object.entries(data.equity).map(([key, value]) => `
          <tr>
            <td class="indent">${key}</td>
            <td class="amount">${value.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
          </tr>
        `).join('')}
        <tr class="subtotal">
          <td>${L.totalEquity}</td>
          <td class="amount">${totalEquity.toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
        </tr>

        <tr class="total">
          <td>${L.totalLiabilitiesEquity}</td>
          <td class="amount">${(totalLiabilities + totalEquity).toLocaleString(fmt, { minimumFractionDigits: 2 })} $</td>
        </tr>
      </table>
    </div>
  </div>

  <div class="footer">
    <p>${L.generatedOn} ${new Date().toLocaleDateString(fmt)}</p>
  </div>
</body>
</html>
  `;
}

/**
 * Generate HTML for Journal Entry
 */
export function generateJournalEntryHTML(entry: JournalEntry, _company: CompanyInfo = DEFAULT_COMPANY, locale?: string): string {
  const L = getLabels(locale);
  const fmt = formatLocale(locale);
  const totalDebits = entry.lines.reduce((sum, l) => sum + l.debit, 0);
  const totalCredits = entry.lines.reduce((sum, l) => sum + l.credit, 0);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${L.journalEntryTitle} ${entry.entryNumber}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11px; padding: 30px; }
    .header { margin-bottom: 20px; }
    .header h1 { font-size: 16px; color: #1a5f7a; }
    .meta { display: flex; gap: 30px; margin: 15px 0; padding: 10px; background: #f8f9fa; border-radius: 4px; }
    .meta-item { }
    .meta-label { color: #666; font-size: 10px; }
    .meta-value { font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th, td { padding: 10px; text-align: left; border: 1px solid #ddd; }
    th { background: #1a5f7a; color: white; }
    td.amount { text-align: right; font-family: 'Courier New', monospace; }
    tr.total { background: #f0f0f0; font-weight: bold; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${L.journalEntryTitle}</h1>
  </div>

  <div class="meta">
    <div class="meta-item">
      <div class="meta-label">${L.entryNumber}</div>
      <div class="meta-value">${entry.entryNumber}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">Date</div>
      <div class="meta-value">${new Date(entry.date).toLocaleDateString(fmt)}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">${L.type}</div>
      <div class="meta-value">${entry.type}</div>
    </div>
    <div class="meta-item">
      <div class="meta-label">${L.status}</div>
      <div class="meta-value">${entry.status}</div>
    </div>
    ${entry.reference ? `
    <div class="meta-item">
      <div class="meta-label">${L.reference}</div>
      <div class="meta-value">${entry.reference}</div>
    </div>
    ` : ''}
  </div>

  <p style="margin: 10px 0;"><strong>Description:</strong> ${entry.description}</p>

  <table>
    <tr>
      <th>${L.account}</th>
      <th>${L.description}</th>
      <th style="text-align: right;">${L.debit}</th>
      <th style="text-align: right;">${L.credit}</th>
    </tr>
    ${entry.lines.map(line => `
      <tr>
        <td>${line.accountCode} - ${line.accountName}</td>
        <td>${line.description || '-'}</td>
        <td class="amount">${line.debit > 0 ? line.debit.toFixed(2) + ' $' : ''}</td>
        <td class="amount">${line.credit > 0 ? line.credit.toFixed(2) + ' $' : ''}</td>
      </tr>
    `).join('')}
    <tr class="total">
      <td colspan="2">${L.total}</td>
      <td class="amount">${totalDebits.toFixed(2)} $</td>
      <td class="amount">${totalCredits.toFixed(2)} $</td>
    </tr>
  </table>

  <p style="margin-top: 20px; color: #666; font-size: 10px;">
    ${L.createdBy}: ${entry.createdBy} | ${new Date(entry.createdAt).toLocaleString(fmt)}
  </p>
</body>
</html>
  `;
}
