/**
 * Seed script for 25 Audit Types
 * Run: npx ts-node --compiler-options '{"module":"CommonJS"}' scripts/seed-audit-types.ts
 */

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

interface AuditTypeSeed {
  code: string;
  name: string;
  nameFr: string;
  description: string;
  descriptionFr: string;
  severity: string;
  category: string;
  sortOrder: number;
  checklist: object[];
}

const auditTypes: AuditTypeSeed[] = [
  // ============== CRITICAL (1-10) ==============
  {
    code: 'AUTH-SESSION',
    name: 'Auth & Session Security',
    nameFr: 'Authentification & Sécurité de Session',
    description: 'Session fixation, token expiry, cookie flags, auth() usage in protected routes, session invalidation',
    descriptionFr: 'Fixation de session, expiration des tokens, flags cookies, utilisation auth() dans routes protégées',
    severity: 'CRITICAL',
    category: 'security',
    sortOrder: 1,
    checklist: [
      { id: 'auth-01', check: 'All protected API routes call auth()', description: 'Every route under /api/admin/ must verify session' },
      { id: 'auth-02', check: 'Cookie httpOnly flag set', description: 'Session cookies must have httpOnly=true' },
      { id: 'auth-03', check: 'Cookie secure flag set', description: 'Session cookies must have secure=true in production' },
      { id: 'auth-04', check: 'Cookie sameSite flag set', description: 'Session cookies should have sameSite=lax or strict' },
      { id: 'auth-05', check: 'Session expiry configured', description: 'Sessions must expire after reasonable time' },
      { id: 'auth-06', check: 'No session token in URL', description: 'Session tokens must never appear in URLs or query params' },
      { id: 'auth-07', check: 'Password change invalidates sessions', description: 'When password changes, all other sessions should be revoked' },
    ],
  },
  {
    code: 'AUTHZ-RBAC',
    name: 'Authorization & RBAC',
    nameFr: 'Autorisation & RBAC',
    description: 'Role checks on admin routes, no privilege escalation, user data isolation',
    descriptionFr: 'Vérification des rôles sur routes admin, pas d\'escalade de privilèges, isolation des données',
    severity: 'CRITICAL',
    category: 'security',
    sortOrder: 2,
    checklist: [
      { id: 'authz-01', check: 'Admin routes check role', description: 'All /api/admin/ routes must verify EMPLOYEE or OWNER role' },
      { id: 'authz-02', check: 'No privilege escalation via ID manipulation', description: 'Users cannot access other users data by changing IDs in requests' },
      { id: 'authz-03', check: 'Owner-only routes protected', description: 'Sensitive routes (settings, permissions) require OWNER role' },
      { id: 'authz-04', check: 'API routes use withAdminGuard', description: 'All admin API routes should use the withAdminGuard wrapper' },
      { id: 'authz-05', check: 'User data scoped to session user', description: 'Customer routes return only data belonging to the authenticated user' },
    ],
  },
  {
    code: 'INPUT-INJECTION',
    name: 'Input Validation & Injection',
    nameFr: 'Validation des Entrées & Injection',
    description: 'Zod schemas on POST/PUT/PATCH, SQL injection, XSS, command injection, path traversal',
    descriptionFr: 'Schémas Zod sur POST/PUT/PATCH, injection SQL, XSS, injection de commandes, traversée de chemin',
    severity: 'CRITICAL',
    category: 'security',
    sortOrder: 3,
    checklist: [
      { id: 'input-01', check: 'POST/PUT/PATCH routes validate input with Zod', description: 'All mutation routes must validate request body' },
      { id: 'input-02', check: 'No raw SQL queries without parameterization', description: '$queryRaw and $executeRaw must use parameterized queries' },
      { id: 'input-03', check: 'No dangerouslySetInnerHTML with user input', description: 'React dangerouslySetInnerHTML must not render unsanitized user content' },
      { id: 'input-04', check: 'No eval() or Function() with user input', description: 'Dynamic code execution with user input is forbidden' },
      { id: 'input-05', check: 'Path parameters validated', description: 'File paths from user input must be validated against traversal attacks' },
      { id: 'input-06', check: 'Query parameters sanitized', description: 'URL query params used in DB queries must be validated' },
    ],
  },
  {
    code: 'CSRF-RATELIMIT',
    name: 'CSRF & Rate Limiting',
    nameFr: 'CSRF & Limitation de Débit',
    description: 'CSRF tokens on state-changing routes, rate limiting on auth/payment/contact endpoints',
    descriptionFr: 'Tokens CSRF sur routes à changement d\'état, limitation de débit sur auth/paiement/contact',
    severity: 'CRITICAL',
    category: 'security',
    sortOrder: 4,
    checklist: [
      { id: 'csrf-01', check: 'State-changing routes validate CSRF', description: 'POST/PUT/PATCH/DELETE routes must validate CSRF token' },
      { id: 'csrf-02', check: 'Auth endpoints rate limited', description: 'Login, register, password reset must have rate limiting' },
      { id: 'csrf-03', check: 'Payment endpoints rate limited', description: 'Checkout and payment routes must have rate limiting' },
      { id: 'csrf-04', check: 'Contact/email endpoints rate limited', description: 'Contact forms and email sends must have rate limiting' },
      { id: 'csrf-05', check: 'Brute force protection on login', description: 'Login attempts should be limited per IP and per account' },
    ],
  },
  {
    code: 'SECRETS-ENV',
    name: 'Secrets & Environment',
    nameFr: 'Secrets & Environnement',
    description: 'No hardcoded secrets, .env in .gitignore, server-only env vars not exposed to client',
    descriptionFr: 'Pas de secrets en dur, .env dans .gitignore, variables serveur non exposées au client',
    severity: 'CRITICAL',
    category: 'security',
    sortOrder: 5,
    checklist: [
      { id: 'secrets-01', check: 'No hardcoded API keys or passwords', description: 'Source code must not contain hardcoded secrets' },
      { id: 'secrets-02', check: '.env files in .gitignore', description: 'All .env files must be excluded from version control' },
      { id: 'secrets-03', check: 'NEXT_PUBLIC_ only on safe values', description: 'Only non-sensitive values should use NEXT_PUBLIC_ prefix' },
      { id: 'secrets-04', check: 'Server env vars not in client bundles', description: 'process.env.SECRET_KEY must not be accessible in client components' },
      { id: 'secrets-05', check: 'No secrets in console.log', description: 'Logging must not output sensitive environment variables' },
    ],
  },
  {
    code: 'PAYMENT-PCI',
    name: 'Payment & PCI Compliance',
    nameFr: 'Paiement & Conformité PCI',
    description: 'Stripe webhook verification, no card data in logs/DB, server-side amount validation',
    descriptionFr: 'Vérification webhook Stripe, pas de données carte dans logs/BD, validation montants côté serveur',
    severity: 'CRITICAL',
    category: 'compliance',
    sortOrder: 6,
    checklist: [
      { id: 'payment-01', check: 'Stripe webhook signature verified', description: 'All Stripe webhook handlers must verify the signature' },
      { id: 'payment-02', check: 'No card data stored in DB', description: 'PAN, CVV, expiry must never be stored' },
      { id: 'payment-03', check: 'No card data in logs', description: 'Log statements must not contain payment card information' },
      { id: 'payment-04', check: 'Amounts validated server-side', description: 'Payment amounts must be calculated server-side, not from client' },
      { id: 'payment-05', check: 'Refund authorization checked', description: 'Refund endpoints must verify authorization' },
      { id: 'payment-06', check: 'Idempotency keys used', description: 'Payment creation should use idempotency keys to prevent double charges' },
    ],
  },
  {
    code: 'ACCOUNTING-INTEGRITY',
    name: 'Accounting Data Integrity',
    nameFr: 'Intégrité des Données Comptables',
    description: 'Double-entry consistency, journal entries balance, GL totals match, tax calculations',
    descriptionFr: 'Cohérence double entrée, équilibre écritures, totaux GL correspondent, calculs taxes',
    severity: 'CRITICAL',
    category: 'integrity',
    sortOrder: 7,
    checklist: [
      { id: 'acct-01', check: 'Journal entries always balance (debit = credit)', description: 'Every journal entry must have equal debits and credits' },
      { id: 'acct-02', check: 'GL account totals match detail', description: 'Account balances must match sum of their journal lines' },
      { id: 'acct-03', check: 'No orphaned journal lines', description: 'Every journal line must belong to a valid journal entry' },
      { id: 'acct-04', check: 'Tax calculations match invoices', description: 'Tax amounts on invoices must be correctly calculated' },
      { id: 'acct-05', check: 'Accounting period locks enforced', description: 'Closed periods must not allow new entries without override' },
    ],
  },
  {
    code: 'TAX-ACCURACY',
    name: 'Tax Calculation Accuracy',
    nameFr: 'Précision des Calculs de Taxes',
    description: 'GST/QST/HST rates correct, tax-exempt handling, rounding, multi-currency',
    descriptionFr: 'Taux TPS/TVQ/TVH corrects, gestion exemptions, arrondissement, multi-devises',
    severity: 'CRITICAL',
    category: 'integrity',
    sortOrder: 8,
    checklist: [
      { id: 'tax-01', check: 'GST rate is 5%', description: 'Federal GST must be calculated at 5%' },
      { id: 'tax-02', check: 'QST rate is 9.975%', description: 'Quebec QST must be calculated at 9.975%' },
      { id: 'tax-03', check: 'HST rates correct per province', description: 'HST rates must match each province (ON=13%, NS/NB/NL/PE=15%)' },
      { id: 'tax-04', check: 'Tax-exempt items handled', description: 'Items marked as exempt must not have tax applied' },
      { id: 'tax-05', check: 'Tax rounding follows bankers rounding', description: 'Tax amounts must use bankers rounding (round half to even)' },
      { id: 'tax-06', check: 'Tax reports match collected amounts', description: 'GST/QST report totals must match actual collected amounts' },
    ],
  },
  {
    code: 'PRIVACY-COMPLIANCE',
    name: 'RGPD/PIPEDA Privacy',
    nameFr: 'Conformité RGPD/PIPEDA',
    description: 'Consent timestamps, data export, data deletion, cookie consent, retention policies',
    descriptionFr: 'Horodatage consentement, export données, suppression données, consentement cookies, rétention',
    severity: 'CRITICAL',
    category: 'compliance',
    sortOrder: 9,
    checklist: [
      { id: 'privacy-01', check: 'Consent timestamps stored', description: 'User consent for data processing must be timestamped' },
      { id: 'privacy-02', check: 'Data export capability exists', description: 'Users must be able to export their personal data' },
      { id: 'privacy-03', check: 'Data deletion capability exists', description: 'Users must be able to request deletion of their data' },
      { id: 'privacy-04', check: 'Cookie consent implemented', description: 'Cookie consent banner must be shown to new visitors' },
      { id: 'privacy-05', check: 'Privacy policy versioned', description: 'Privacy policy changes must be tracked with versions' },
      { id: 'privacy-06', check: 'Data retention policies defined', description: 'How long different data types are retained must be documented' },
    ],
  },
  {
    code: 'DB-INTEGRITY',
    name: 'Database Integrity',
    nameFr: 'Intégrité de la Base de Données',
    description: 'Foreign keys, cascading deletes, orphaned records, unique constraints, required fields',
    descriptionFr: 'Clés étrangères, suppressions en cascade, enregistrements orphelins, contraintes uniques, champs requis',
    severity: 'CRITICAL',
    category: 'integrity',
    sortOrder: 10,
    checklist: [
      { id: 'db-01', check: 'Foreign key constraints exist on all relations', description: 'All Prisma relations must have corresponding DB foreign keys' },
      { id: 'db-02', check: 'Cascading deletes configured correctly', description: 'onDelete behavior must be appropriate for each relation' },
      { id: 'db-03', check: 'No orphaned records in DB', description: 'Records referencing non-existent parents must be identified' },
      { id: 'db-04', check: 'Unique constraints on business keys', description: 'Email, slug, code fields must have unique constraints' },
      { id: 'db-05', check: 'Required fields are not nullable', description: 'Business-critical fields must not allow NULL values' },
      { id: 'db-06', check: 'Indexes on frequently queried columns', description: 'Columns used in WHERE/JOIN must have database indexes' },
    ],
  },
  // ============== HIGH (11-19) ==============
  {
    code: 'RACE-CONDITIONS',
    name: 'Race Conditions & Concurrency',
    nameFr: 'Conditions de Course & Concurrence',
    description: 'Stock updates use transactions, order creation atomic, payment processing idempotent',
    descriptionFr: 'Mises à jour stock en transactions, création commandes atomique, paiements idempotents',
    severity: 'HIGH',
    category: 'integrity',
    sortOrder: 11,
    checklist: [
      { id: 'race-01', check: 'Stock updates wrapped in transactions', description: 'Inventory changes must use database transactions' },
      { id: 'race-02', check: 'Order creation is atomic', description: 'Creating an order with items must be a single transaction' },
      { id: 'race-03', check: 'Payment processing is idempotent', description: 'Duplicate payment requests must not create double charges' },
      { id: 'race-04', check: 'Optimistic locking where needed', description: 'Concurrent updates to same record should use version checking' },
    ],
  },
  {
    code: 'API-LEAKAGE',
    name: 'API Data Leakage',
    nameFr: 'Fuite de Données API',
    description: 'No password hashes in responses, select only needed fields, safe error messages',
    descriptionFr: 'Pas de hashes mot de passe dans réponses, select champs nécessaires, messages erreur sûrs',
    severity: 'HIGH',
    category: 'security',
    sortOrder: 12,
    checklist: [
      { id: 'leak-01', check: 'No password hashes in API responses', description: 'hashedPassword must never appear in JSON responses' },
      { id: 'leak-02', check: 'Select only needed fields', description: 'Prisma queries should use select to limit returned fields' },
      { id: 'leak-03', check: 'Error messages dont leak internals', description: 'Error responses must not expose stack traces or internal paths' },
      { id: 'leak-04', check: 'No internal IDs exposed unnecessarily', description: 'Internal system IDs should be hidden when not needed by client' },
    ],
  },
  {
    code: 'DB-PERFORMANCE',
    name: 'Database Performance',
    nameFr: 'Performance Base de Données',
    description: 'N+1 query detection, missing indexes, query count per page, slow queries',
    descriptionFr: 'Détection requêtes N+1, index manquants, nombre requêtes par page, requêtes lentes',
    severity: 'HIGH',
    category: 'performance',
    sortOrder: 13,
    checklist: [
      { id: 'perf-01', check: 'No N+1 query patterns', description: 'Loops making individual DB queries should use include/join instead' },
      { id: 'perf-02', check: 'Indexes on filtered/joined columns', description: 'Columns in WHERE and JOIN must have indexes' },
      { id: 'perf-03', check: 'Reasonable query count per page', description: 'Pages should not make more than 10 DB queries' },
      { id: 'perf-04', check: 'Large result sets paginated', description: 'Queries returning many rows must use pagination' },
    ],
  },
  {
    code: 'WEBHOOK-IDEMPOTENCY',
    name: 'Webhook & Idempotency',
    nameFr: 'Webhooks & Idempotence',
    description: 'Stripe webhooks idempotent, duplicate event handling, retry tolerance',
    descriptionFr: 'Webhooks Stripe idempotents, gestion doublons, tolérance aux retries',
    severity: 'HIGH',
    category: 'integrity',
    sortOrder: 14,
    checklist: [
      { id: 'webhook-01', check: 'Webhook handlers are idempotent', description: 'Processing same webhook event twice must produce same result' },
      { id: 'webhook-02', check: 'Duplicate events handled gracefully', description: 'Duplicate Stripe event IDs should be detected and skipped' },
      { id: 'webhook-03', check: 'Webhook retry tolerance', description: 'Failed webhook processing must not corrupt data on retry' },
      { id: 'webhook-04', check: 'Event ordering handled', description: 'Out-of-order webhook events must be handled correctly' },
    ],
  },
  {
    code: 'CRON-RELIABILITY',
    name: 'Cron & Background Jobs',
    nameFr: 'Cron & Tâches en Arrière-plan',
    description: 'Error handling, retry logic, overlap prevention, timeout protection, logging',
    descriptionFr: 'Gestion erreurs, logique de retry, prévention chevauchement, protection timeout, journalisation',
    severity: 'HIGH',
    category: 'integrity',
    sortOrder: 15,
    checklist: [
      { id: 'cron-01', check: 'Cron jobs have error handling', description: 'Background jobs must catch and log errors' },
      { id: 'cron-02', check: 'Retry logic with backoff', description: 'Failed jobs should retry with exponential backoff' },
      { id: 'cron-03', check: 'No overlapping executions', description: 'Long-running jobs must prevent concurrent execution' },
      { id: 'cron-04', check: 'Timeout protection', description: 'Jobs must have maximum execution time limits' },
    ],
  },
  {
    code: 'EMAIL-CASL',
    name: 'Email & CASL Compliance',
    nameFr: 'Email & Conformité LCAP',
    description: 'Unsubscribe links, consent before marketing, transactional vs marketing separation',
    descriptionFr: 'Liens désabonnement, consentement avant marketing, séparation transactionnel/marketing',
    severity: 'HIGH',
    category: 'compliance',
    sortOrder: 16,
    checklist: [
      { id: 'casl-01', check: 'Unsubscribe links in all marketing emails', description: 'Every marketing email must contain an unsubscribe link' },
      { id: 'casl-02', check: 'Consent recorded before marketing emails', description: 'Marketing emails require express consent (CASL)' },
      { id: 'casl-03', check: 'Transactional vs marketing separated', description: 'Order confirmations and marketing should use different channels/logic' },
      { id: 'casl-04', check: 'Sender identity correct', description: 'From name and address must identify the sender clearly' },
    ],
  },
  {
    code: 'I18N-COMPLETENESS',
    name: 'i18n Completeness',
    nameFr: 'Complétude i18n',
    description: 'All strings have fr+en translations, no hardcoded strings, locale-aware formatting',
    descriptionFr: 'Toutes les chaînes ont des traductions fr+en, pas de chaînes en dur, formatage selon locale',
    severity: 'HIGH',
    category: 'quality',
    sortOrder: 17,
    checklist: [
      { id: 'i18n-01', check: 'All t() keys exist in fr.json and en.json', description: 'Every translation key used must exist in both reference locales' },
      { id: 'i18n-02', check: 'No hardcoded strings in components', description: 'User-facing text must use t() function' },
      { id: 'i18n-03', check: 'Date formatting is locale-aware', description: 'Dates must be formatted according to user locale' },
      { id: 'i18n-04', check: 'Currency formatting is locale-aware', description: 'Currency amounts must use locale-appropriate formatting' },
      { id: 'i18n-05', check: 'All 22 locale files have same keys', description: 'No locale file should be missing keys present in en.json' },
    ],
  },
  {
    code: 'WEBAUTHN-MFA',
    name: 'WebAuthn & MFA',
    nameFr: 'WebAuthn & AMF',
    description: 'MFA enrollment flow, recovery codes, WebAuthn registration/authentication',
    descriptionFr: 'Flux inscription AMF, codes de récupération, inscription/authentification WebAuthn',
    severity: 'HIGH',
    category: 'security',
    sortOrder: 18,
    checklist: [
      { id: 'mfa-01', check: 'MFA enrollment flow complete', description: 'Users can enable/disable MFA from their account settings' },
      { id: 'mfa-02', check: 'Recovery codes work', description: 'Recovery codes must successfully bypass MFA when used' },
      { id: 'mfa-03', check: 'WebAuthn registration works', description: 'Users can register a security key or biometric' },
      { id: 'mfa-04', check: 'Fallback mechanisms exist', description: 'Users locked out of MFA must have a recovery path' },
    ],
  },
  {
    code: 'SECURITY-HEADERS',
    name: 'Security Headers',
    nameFr: 'En-têtes de Sécurité',
    description: 'CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, HSTS',
    descriptionFr: 'CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, HSTS',
    severity: 'HIGH',
    category: 'security',
    sortOrder: 19,
    checklist: [
      { id: 'headers-01', check: 'Content-Security-Policy configured', description: 'CSP header must restrict script and style sources' },
      { id: 'headers-02', check: 'X-Frame-Options set', description: 'Must be DENY or SAMEORIGIN to prevent clickjacking' },
      { id: 'headers-03', check: 'X-Content-Type-Options: nosniff', description: 'Prevents MIME type sniffing' },
      { id: 'headers-04', check: 'Referrer-Policy configured', description: 'Controls how much referrer info is sent with requests' },
      { id: 'headers-05', check: 'HSTS enabled in production', description: 'Strict-Transport-Security header must be set' },
      { id: 'headers-06', check: 'Permissions-Policy configured', description: 'Controls browser features (camera, mic, geolocation)' },
    ],
  },
  // ============== MEDIUM (20-24) ==============
  {
    code: 'TYPESCRIPT-QUALITY',
    name: 'TypeScript Quality',
    nameFr: 'Qualité TypeScript',
    description: 'No any types, strict mode, proper error typing, Prisma types match schema',
    descriptionFr: 'Pas de type any, mode strict, typage erreurs correct, types Prisma correspondent au schéma',
    severity: 'MEDIUM',
    category: 'quality',
    sortOrder: 20,
    checklist: [
      { id: 'ts-01', check: 'Minimal use of any type', description: 'any type should be avoided; use unknown or specific types' },
      { id: 'ts-02', check: 'Strict mode enabled', description: 'tsconfig.json must have strict: true' },
      { id: 'ts-03', check: 'Error types are specific', description: 'catch blocks should type errors properly, not use any' },
      { id: 'ts-04', check: 'No type assertions without justification', description: 'as X casts should have comments explaining why' },
    ],
  },
  {
    code: 'FRONTEND-PERFORMANCE',
    name: 'Frontend Performance',
    nameFr: 'Performance Frontend',
    description: 'Bundle size, image optimization, lazy loading, Core Web Vitals',
    descriptionFr: 'Taille des bundles, optimisation images, chargement différé, Core Web Vitals',
    severity: 'MEDIUM',
    category: 'performance',
    sortOrder: 21,
    checklist: [
      { id: 'fe-01', check: 'Images use next/image', description: 'All images should use Next.js Image component for optimization' },
      { id: 'fe-02', check: 'Lazy loading for below-fold content', description: 'Components below the fold should use dynamic imports' },
      { id: 'fe-03', check: 'No unnecessary re-renders', description: 'Components should use memo/useMemo where appropriate' },
      { id: 'fe-04', check: 'Proper Suspense usage', description: 'Async components should be wrapped in Suspense boundaries' },
    ],
  },
  {
    code: 'ERROR-OBSERVABILITY',
    name: 'Error Handling & Observability',
    nameFr: 'Gestion des Erreurs & Observabilité',
    description: 'Try/catch logging, structured logging, error boundaries, graceful degradation',
    descriptionFr: 'Journalisation try/catch, logs structurés, frontières d\'erreur, dégradation gracieuse',
    severity: 'MEDIUM',
    category: 'quality',
    sortOrder: 22,
    checklist: [
      { id: 'err-01', check: 'All try/catch blocks log errors', description: 'Caught errors must be logged with context' },
      { id: 'err-02', check: 'Structured logging with context', description: 'Log entries should include request ID, user, action' },
      { id: 'err-03', check: 'Error boundaries on pages', description: 'Pages should have error.tsx error boundaries' },
      { id: 'err-04', check: 'Graceful degradation', description: 'Failed API calls should show fallback UI, not crash' },
    ],
  },
  {
    code: 'ARCHITECTURE-QUALITY',
    name: 'Architecture Quality',
    nameFr: 'Qualité Architecturale',
    description: 'No circular dependencies, separation of concerns, consistent patterns, no dead code',
    descriptionFr: 'Pas de dépendances circulaires, séparation des responsabilités, patterns cohérents, pas de code mort',
    severity: 'MEDIUM',
    category: 'quality',
    sortOrder: 23,
    checklist: [
      { id: 'arch-01', check: 'No circular dependencies', description: 'Module A importing B importing A creates circular deps' },
      { id: 'arch-02', check: 'Consistent code patterns', description: 'Similar features should follow the same structure' },
      { id: 'arch-03', check: 'Proper separation of concerns', description: 'Business logic in lib/, UI in components/, data in API routes' },
      { id: 'arch-04', check: 'No dead/unreachable code', description: 'Unused exports and unreachable code should be removed' },
    ],
  },
  {
    code: 'ACCESSIBILITY-WCAG',
    name: 'Accessibility WCAG 2.1',
    nameFr: 'Accessibilité WCAG 2.1',
    description: 'Alt text, keyboard navigation, ARIA labels, color contrast, focus management',
    descriptionFr: 'Texte alt, navigation clavier, labels ARIA, contraste couleurs, gestion du focus',
    severity: 'MEDIUM',
    category: 'quality',
    sortOrder: 24,
    checklist: [
      { id: 'a11y-01', check: 'Images have alt text', description: 'All img elements must have meaningful alt attributes' },
      { id: 'a11y-02', check: 'Keyboard navigation works', description: 'All interactive elements must be reachable via keyboard' },
      { id: 'a11y-03', check: 'ARIA labels on interactive elements', description: 'Buttons and links must have accessible names' },
      { id: 'a11y-04', check: 'Sufficient color contrast', description: 'Text must meet WCAG AA contrast ratio (4.5:1)' },
      { id: 'a11y-05', check: 'Focus management on navigation', description: 'Focus should move logically when navigating' },
    ],
  },
  // ============== LOW (25) ==============
  {
    code: 'API-CONTRACTS',
    name: 'API Contract Validation',
    nameFr: 'Validation des Contrats API',
    description: 'Response shapes consistent, error format standardized, HTTP status codes correct',
    descriptionFr: 'Formes de réponse cohérentes, format d\'erreur standardisé, codes HTTP corrects',
    severity: 'LOW',
    category: 'quality',
    sortOrder: 25,
    checklist: [
      { id: 'api-01', check: 'Response shapes are consistent', description: 'Similar endpoints should return same shape (data, error, pagination)' },
      { id: 'api-02', check: 'Error format standardized', description: 'All errors should follow { error: string, status: number } pattern' },
      { id: 'api-03', check: 'HTTP status codes correct', description: '200 for success, 201 for creation, 400 for bad input, 401/403 for auth' },
      { id: 'api-04', check: 'Pagination consistent', description: 'All list endpoints should use same pagination pattern' },
    ],
  },
  // ============== ADDITIONAL (26-27) ==============
  {
    code: 'AZURE-LOCAL-SYNC',
    name: 'Azure-Local Sync',
    nameFr: 'Synchronisation Azure-Local',
    description: 'Compare local codebase and DB with Azure deployment: files, sizes, row counts',
    descriptionFr: 'Comparer le code local et la BD avec le déploiement Azure: fichiers, tailles, comptes de lignes',
    severity: 'HIGH',
    category: 'integrity',
    sortOrder: 26,
    checklist: [
      { id: 'sync-01', check: 'Azure deployment credentials configured', description: 'AZURE_WEBAPP_NAME, AZURE_DEPLOY_USER, AZURE_DEPLOY_PASSWORD must be set' },
      { id: 'sync-02', check: 'All critical deployment files present', description: 'package.json, next.config, prisma/schema.prisma, etc. must exist locally' },
      { id: 'sync-03', check: 'Build output is fresh', description: '.next directory must have a recent BUILD_ID' },
      { id: 'sync-04', check: 'Required environment variables defined', description: 'DATABASE_URL, NEXTAUTH_SECRET, STRIPE keys must be in .env' },
      { id: 'sync-05', check: 'Prisma schema and client in sync', description: 'Schema has models, Prisma client is generated' },
      { id: 'sync-06', check: 'Deployment configuration exists', description: 'GitHub Actions, Dockerfile, or web.config present' },
      { id: 'sync-07', check: 'Files match Azure via Kudu API', description: 'Critical files on Azure match local versions in name and size' },
      { id: 'sync-08', check: 'Database row counts match', description: 'Core table counts match between local and Azure PostgreSQL' },
    ],
  },
  {
    code: 'ADMIN-BACKEND-MEGA',
    name: 'Admin Backend Mega Audit',
    nameFr: 'Méga Audit Backend Admin',
    description: 'Comprehensive admin panel audit: pages, navigation, API routes, guards, i18n',
    descriptionFr: 'Audit complet du panneau admin: pages, navigation, routes API, gardes, i18n',
    severity: 'HIGH',
    category: 'quality',
    sortOrder: 27,
    checklist: [
      { id: 'admin-01', check: 'No stub/placeholder admin pages', description: 'All admin pages should have real functional content' },
      { id: 'admin-02', check: 'Navigation links point to existing pages', description: 'All sidebar hrefs must resolve to a real page.tsx' },
      { id: 'admin-03', check: 'Admin pages reference existing API routes', description: 'fetch() calls in admin pages must point to existing API routes' },
      { id: 'admin-04', check: 'Admin API routes have auth guards', description: 'All /api/admin/ routes must use withAdminGuard or auth()' },
      { id: 'admin-05', check: 'Admin layout has auth and error handling', description: 'layout.tsx, error.tsx, and loading.tsx should exist for admin' },
      { id: 'admin-06', check: 'Admin pages use i18n', description: 'All admin pages should use useI18n or useTranslations for localization' },
    ],
  },
];

async function main() {
  console.log('Seeding 27 audit types...');

  for (const auditType of auditTypes) {
    await prisma.auditType.upsert({
      where: { code: auditType.code },
      update: {
        name: auditType.name,
        nameFr: auditType.nameFr,
        description: auditType.description,
        descriptionFr: auditType.descriptionFr,
        severity: auditType.severity,
        category: auditType.category,
        sortOrder: auditType.sortOrder,
        checklist: JSON.stringify(auditType.checklist),
      },
      create: {
        code: auditType.code,
        name: auditType.name,
        nameFr: auditType.nameFr,
        description: auditType.description,
        descriptionFr: auditType.descriptionFr,
        severity: auditType.severity,
        category: auditType.category,
        sortOrder: auditType.sortOrder,
        checklist: JSON.stringify(auditType.checklist),
      },
    });
    console.log(`  ✓ ${auditType.code} - ${auditType.name}`);
  }

  console.log(`\nDone! Seeded ${auditTypes.length} audit types.`);
}

main()
  .catch((e) => {
    console.error('Error seeding audit types:', e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
